export const macKeyMap = {
  ArrowUp: "↑",
  ArrowRight: "→",
  ArrowDown: "↓",
  ArrowLeft: "←",
  Shift: "⇧",
  Meta: "⌘",
  Alt: "⌥",
  Control: "^",
  Escape: "esc",
  Backspace: "⌫",
  Enter: "⏎",
  " ": "space",
  CapsLock: "caps lock",
  Tab: "tab",
};

export const winKeyMap = {
  ArrowUp: "↑",
  ArrowRight: "→",
  ArrowDown: "↓",
  ArrowLeft: "←",
  Shift: "Shift",
  Meta: "Win",
  Alt: "Alt",
  Control: "Ctrl",
  Escape: "Esc",
  Backspace: "←",
  Enter: "Enter",
  " ": "space",
  CapsLock: "Caps",
  Tab: "Tab",
};
